<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DustInTheWind.ErrorFlow.AspNetCore" Version="1.2.2" />
		<PackageReference Include="RequestR" Version="2.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CaveOfWonders.Cli.Application\CaveOfWonders.Cli.Application.csproj" PrivateAssets="All" />
		<ProjectReference Include="..\CaveOfWonders.DataTypes\CaveOfWonders.DataTypes.csproj" PrivateAssets="All" />
		<ProjectReference Include="..\CaveOfWonders.Infrastructure\CaveOfWonders.Infrastructure.csproj" PrivateAssets="All" />
	</ItemGroup>

</Project>
