// <auto-generated />
using System;
using DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.Migrations
{
    [DbContext(typeof(CaveOfWondersDbContext))]
    [Migration("20260720114148_AddGemPotIdExternalIdIndex")]
    partial class AddGemPotIdExternalIdIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.Entities.AverageWageEntity", b =>
                {
                    b.Property<int>("Year")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("GrossValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NetValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Year");

                    b.ToTable("AverageWages");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.Entities.CpiEntity", b =>
                {
                    b.Property<int>("Year")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Year");

                    b.ToTable("Cpis");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.Entities.ExchangeRateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyPair")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date", "CurrencyPair")
                        .IsUnique();

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.Entities.GemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PotId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PotId", "ExternalId");

                    b.ToTable("Gems");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.Entities.GemParameterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GemId");

                    b.ToTable("GemParameters");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.Entities.PotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<uint>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pots");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.Entities.PotLabelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PotId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PotId");

                    b.ToTable("PotLabels");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.Entities.PotSnapshotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PotId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PotId", "Date")
                        .IsUnique();

                    b.ToTable("PotSnapshots");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.Entities.GemEntity", b =>
                {
                    b.HasOne("DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.Entities.PotEntity", "Pot")
                        .WithMany()
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pot");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.Entities.GemParameterEntity", b =>
                {
                    b.HasOne("DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.Entities.GemEntity", "Gem")
                        .WithMany("Parameters")
                        .HasForeignKey("GemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gem");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.Entities.PotLabelEntity", b =>
                {
                    b.HasOne("DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.Entities.PotEntity", "Pot")
                        .WithMany("Labels")
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pot");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.Entities.PotSnapshotEntity", b =>
                {
                    b.HasOne("DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.Entities.PotEntity", "Pot")
                        .WithMany("Snapshots")
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pot");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.Entities.GemEntity", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.Entities.PotEntity", b =>
                {
                    b.Navigation("Labels");

                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
