// <auto-generated />
using System;
using DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.Migrations
{
    [DbContext(typeof(CaveOfWondersDbContext))]
    partial class CaveOfWondersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Domain.AverageWage", b =>
                {
                    b.Property<int>("Year")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("GrossValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NetValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Year");

                    b.ToTable("AverageWages");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Domain.Cpi", b =>
                {
                    b.Property<int>("Year")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Year");

                    b.ToTable("Cpis");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Domain.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyPair")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date", "CurrencyPair")
                        .IsUnique();

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Domain.Gem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PotId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PotId", "ExternalId");

                    b.ToTable("Gems");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Domain.Pot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<uint>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pots");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Domain.PotSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PotId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PotId", "Date")
                        .IsUnique();

                    b.ToTable("PotSnapshots");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Domain.Gem", b =>
                {
                    b.HasOne("DustInTheWind.CaveOfWonders.Domain.Pot", "Pot")
                        .WithMany()
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("DustInTheWind.CaveOfWonders.Domain.GemParameter", "Parameters", b1 =>
                        {
                            b1.Property<Guid>("GemId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Key")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT");

                            b1.HasKey("GemId", "Key");

                            b1.ToTable("GemParameters", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GemId");
                        });

                    b.Navigation("Parameters");

                    b.Navigation("Pot");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Domain.Pot", b =>
                {
                    b.OwnsMany("DustInTheWind.CaveOfWonders.Domain.PotLabel", "Labels", b1 =>
                        {
                            b1.Property<Guid>("PotId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Label")
                                .HasColumnType("TEXT");

                            b1.HasKey("PotId", "Label");

                            b1.ToTable("PotLabels", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PotId");
                        });

                    b.Navigation("Labels");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Domain.PotSnapshot", b =>
                {
                    b.HasOne("DustInTheWind.CaveOfWonders.Domain.Pot", "Pot")
                        .WithMany("Snapshots")
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pot");
                });

            modelBuilder.Entity("DustInTheWind.CaveOfWonders.Domain.Pot", b =>
                {
                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
