// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.CompiledModels
{
    public partial class CaveOfWondersDbContextModel
    {
        private CaveOfWondersDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("fbccf24e-9df5-4ee9-8087-7b77c456be9b"), entityTypeCount: 8)
        {
        }

        partial void Initialize()
        {
            var averageWageEntity = AverageWageEntityEntityType.Create(this);
            var cpiEntity = CpiEntityEntityType.Create(this);
            var exchangeRateEntity = ExchangeRateEntityEntityType.Create(this);
            var gemEntity = GemEntityEntityType.Create(this);
            var gemParameterEntity = GemParameterEntityEntityType.Create(this);
            var potEntity = PotEntityEntityType.Create(this);
            var potLabelEntity = PotLabelEntityEntityType.Create(this);
            var potSnapshotEntity = PotSnapshotEntityEntityType.Create(this);

            GemEntityEntityType.CreateForeignKey1(gemEntity, potEntity);
            GemParameterEntityEntityType.CreateForeignKey1(gemParameterEntity, gemEntity);
            PotLabelEntityEntityType.CreateForeignKey1(potLabelEntity, potEntity);
            PotSnapshotEntityEntityType.CreateForeignKey1(potSnapshotEntity, potEntity);

            AverageWageEntityEntityType.CreateAnnotations(averageWageEntity);
            CpiEntityEntityType.CreateAnnotations(cpiEntity);
            ExchangeRateEntityEntityType.CreateAnnotations(exchangeRateEntity);
            GemEntityEntityType.CreateAnnotations(gemEntity);
            GemParameterEntityEntityType.CreateAnnotations(gemParameterEntity);
            PotEntityEntityType.CreateAnnotations(potEntity);
            PotLabelEntityEntityType.CreateAnnotations(potLabelEntity);
            PotSnapshotEntityEntityType.CreateAnnotations(potSnapshotEntity);

            AddAnnotation("ProductVersion", "9.0.18");
        }
    }
}
