// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace DustInTheWind.CaveOfWonders.Adapters.DataAccess.SQLite.CompiledModels
{
    public partial class CaveOfWondersDbContextModel
    {
        private CaveOfWondersDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("7bb091c3-4616-44c5-ac85-a70e9f593ddc"), entityTypeCount: 8)
        {
        }

        partial void Initialize()
        {
            var averageWage = AverageWageEntityType.Create(this);
            var cpi = CpiEntityType.Create(this);
            var exchangeRate = ExchangeRateEntityType.Create(this);
            var gem = GemEntityType.Create(this);
            var gemParameter = GemParameterEntityType.Create(this);
            var pot = PotEntityType.Create(this);
            var potLabel = PotLabelEntityType.Create(this);
            var potSnapshot = PotSnapshotEntityType.Create(this);

            GemEntityType.CreateForeignKey1(gem, pot);
            GemParameterEntityType.CreateForeignKey1(gemParameter, gem);
            PotLabelEntityType.CreateForeignKey1(potLabel, pot);
            PotSnapshotEntityType.CreateForeignKey1(potSnapshot, pot);

            AverageWageEntityType.CreateAnnotations(averageWage);
            CpiEntityType.CreateAnnotations(cpi);
            ExchangeRateEntityType.CreateAnnotations(exchangeRate);
            GemEntityType.CreateAnnotations(gem);
            GemParameterEntityType.CreateAnnotations(gemParameter);
            PotEntityType.CreateAnnotations(pot);
            PotLabelEntityType.CreateAnnotations(potLabel);
            PotSnapshotEntityType.CreateAnnotations(potSnapshot);

            AddAnnotation("ProductVersion", "9.0.18");
        }
    }
}
